### ISSUE TITLE
OS X portability?

### ISSUE THREAD

**Issue by backus** [dkubb/git-tools#1]
It looks like some of the tools don't work on OS X because of differences between grep and the FreeBSD grep binary.  For example, the `git prune-all` command yields the following output:

```sh
git prune-all                                                                                                                                                                                         [ruby-2.2.2]
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]
xargs: illegal option -- -
usage: xargs [-0opt] [-E eofstr] [-I replstr [-R replacements]] [-J replstr]
             [-L number] [-n number [-x]] [-P maxprocs] [-s size]
             [utility [argument ...]]
```

I'm not asking you to fix it or anything, but if I do find the time to make the scripts work on OS X by adding some conditionals then would you be open to a PR?

**Comment by dkubb** [comment]
@backus sure, if it continues to work with GNU grep I'm all for making it portable.

FWIW, I use OSX but I have GNU grep installed because I prefer to have something more consistent in my everyday work with production systems (which are Linux). Even still I have no problem with making it more portable OOTB.

**Comment by tjchambers** [comment]
@backus I am using OS X and would appreciate any work you do on making this work on OS X. In the interim I will look into installing GNU grep on my system.
